# Generated by Django 5.0.1 on 2024-01-28 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderFoodApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
    ]
