# Generated by Django 5.0.1 on 2024-02-10 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderFoodApp', '0003_booking_restaurant_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='id',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
